Update btc-auto-scanner.yml

diff --git a/.github/workflows/btc-auto-scanner.yml b/.github/workflows/btc-auto-scanner.yml
--- a/.github/workflows/btc-auto-scanner.yml
+++ b/.github/workflows/btc-auto-scanner.yml
@@ -1,1 +1,48 @@
+name: Scanner Data Update
 
+on:
+  push:
+    branches:
+      - main
+  schedule:
+    - cron: "0 */1 * * *"
+  workflow_dispatch:       # Allow manual run
+  
+permissions:
+  contents: write
+  pull-requests: write
+
+jobs:
+  update-data:
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v2      
+      with:
+        persist-credentials: false
+        fetch-depth: 0
+
+    - name: Set up Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '14'
+
+    - name: Install dependencies
+      run: npm install
+
+    - name: Fetch BTCUSD Market Scanner Data
+      run: |
+        node index.js || echo "Failed to fetch data"
+
+    - name: Run Bot Task
+      run: |
+        chmod +x ./index.sh
+        ./index.sh
+
+    - name: Commit and push if there are changes
+      uses: ad-m/github-push-action@master
+      with:
+        force: true
+        directory: "."
+        branch: main
+        github_token: ${{ secrets.GITHUB_TOKEN }}
